package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writeGo writes src to a uniquely named Go file in dir and returns its path.
//
// It exists so the cases below read as source-in, findings-out. doccheck's unit of work is a file on
// disk, and a test that fed it an already-parsed AST would skip the part most likely to be wrong.
func writeGo(t *testing.T, dir, name, src string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(src), 0o600); err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
	return path
}

// TestCheckFileFindsUndocumentedDeclarations covers the cases doccheck exists to catch.
//
// The unexported cases are the point of the tool: revive's exported rule already covers the others,
// and if doccheck only agreed with revive there would be no reason to ship it.
func TestCheckFileFindsUndocumentedDeclarations(t *testing.T) {
	dir := t.TempDir()
	src := `package sample

type Exported struct{}

type unexported struct{}

func Exported1() {}

func unexported1() {}

func (u unexported) method() {}

// documented is fine and should not be reported.
func documented() {}

type Iface interface {
	Undocumented() error
}
`
	path := writeGo(t, dir, "sample.go", src)
	findings, err := checkFile(path, config{})
	if err != nil {
		t.Fatalf("checkFile: %v", err)
	}

	want := []string{"Exported", "unexported", "Exported1", "unexported1",
		"unexported.method", "Iface", "Iface.Undocumented"}
	got := map[string]bool{}
	for _, f := range findings {
		got[f.name] = true
	}
	for _, name := range want {
		if !got[name] {
			t.Errorf("%s was not reported as undocumented", name)
		}
	}
	if got["documented"] {
		t.Error("documented was reported despite having a doc comment")
	}
	if len(findings) != len(want) {
		t.Errorf("got %d findings, want %d: %v", len(findings), len(want), findings)
	}
}

// TestCheckFileRequiresTheCommentToNameTheDeclaration covers the copied-comment case.
//
// A comment that names a different declaration is the signature of a block copied from above and half
// edited, which produces a file that passes a presence check and helps nobody.
func TestCheckFileRequiresTheCommentToNameTheDeclaration(t *testing.T) {
	dir := t.TempDir()
	src := `package sample

// somethingElse does a thing for reasons.
func actualName() {}
`
	findings, err := checkFile(writeGo(t, dir, "sample.go", src), config{})
	if err != nil {
		t.Fatalf("checkFile: %v", err)
	}
	if len(findings) != 1 {
		t.Fatalf("got %d findings, want 1: %v", len(findings), findings)
	}
	if !strings.Contains(findings[0].why, "should begin with") {
		t.Errorf("finding %q does not explain the naming rule", findings[0].why)
	}
}

// TestCheckFileAcceptsMethodCommentsStartingWithTheBareName covers Go's own convention.
//
// Method comments conventionally begin with the method name and not Type.Method, so a check that
// demanded the qualified form would fail every correctly written file in the standard library.
func TestCheckFileAcceptsMethodCommentsStartingWithTheBareName(t *testing.T) {
	dir := t.TempDir()
	src := `package sample

// thing is a thing that exists to be a receiver in this test.
type thing struct{}

// do performs the operation and exists to prove the bare-name convention is accepted.
func (t thing) do() {}

// ptr performs the operation on a pointer receiver, which resolves through StarExpr.
func (t *thing) ptr() {}
`
	findings, err := checkFile(writeGo(t, dir, "sample.go", src), config{})
	if err != nil {
		t.Fatalf("checkFile: %v", err)
	}
	if len(findings) != 0 {
		t.Errorf("well-documented methods were reported: %v", findings)
	}
}

// TestCheckFileSkipsGeneratedCode covers the generated-file exemption.
//
// Requiring rationale on generated output would mean either editing something the next run discards or
// adding an exemption comment to every file, and the first exemption is how a rule like this stops
// being taken seriously.
func TestCheckFileSkipsGeneratedCode(t *testing.T) {
	dir := t.TempDir()
	src := `// Code generated by stringer. DO NOT EDIT.

package sample

type Undocumented struct{}

func alsoUndocumented() {}
`
	findings, err := checkFile(writeGo(t, dir, "sample.go", src), config{})
	if err != nil {
		t.Fatalf("checkFile: %v", err)
	}
	if len(findings) != 0 {
		t.Errorf("generated file produced findings: %v", findings)
	}
}

// TestMinWordsIsOffByDefault asserts the length heuristic does not fire unless asked for.
//
// CONTRIBUTING.md promises that presence is machine-checked and quality is review-checked. A default
// that quietly enforced a word count would make that promise false.
func TestMinWordsIsOffByDefault(t *testing.T) {
	dir := t.TempDir()
	src := `package sample

// terse does it.
func terse() {}
`
	path := writeGo(t, dir, "sample.go", src)

	findings, err := checkFile(path, config{})
	if err != nil {
		t.Fatalf("checkFile: %v", err)
	}
	if len(findings) != 0 {
		t.Errorf("the default configuration reported a short comment: %v", findings)
	}

	findings, err = checkFile(path, config{minWords: 10})
	if err != nil {
		t.Fatalf("checkFile: %v", err)
	}
	if len(findings) != 1 {
		t.Errorf("min-words=10 did not report a three-word comment: %v", findings)
	}
}

// TestCheckPathSkipsVendorAndTestdata asserts the directory walk honours its exclusions.
//
// Without this, running doccheck at the repository root after any dependency vendoring would bury the
// real findings under thousands from other people's code, which is the practical way a linter gets
// removed from CI.
func TestCheckPathSkipsVendorAndTestdata(t *testing.T) {
	dir := t.TempDir()
	for _, sub := range []string{"vendor", "testdata", "node_modules"} {
		if err := os.MkdirAll(filepath.Join(dir, sub), 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", sub, err)
		}
		writeGo(t, filepath.Join(dir, sub), "x.go", "package x\n\nfunc undocumented() {}\n")
	}
	writeGo(t, dir, "real.go", "package sample\n\nfunc alsoUndocumented() {}\n")

	findings, err := checkPath(dir, config{})
	if err != nil {
		t.Fatalf("checkPath: %v", err)
	}
	if len(findings) != 1 || findings[0].name != "alsoUndocumented" {
		t.Errorf("checkPath did not skip excluded directories: %v", findings)
	}
}

// TestCheckPathHonoursTheTestsFlag asserts _test.go files can be excluded.
//
// HostSeal checks its own test files, because a guarantee test whose reason for existing is not written
// down is one a future maintainer deletes to make a build pass. The flag exists for consumers of this
// tool who make the other choice.
func TestCheckPathHonoursTheTestsFlag(t *testing.T) {
	dir := t.TempDir()
	writeGo(t, dir, "x_test.go", "package sample\n\nfunc undocumented() {}\n")

	if f, err := checkPath(dir, config{includeTests: true}); err != nil || len(f) != 1 {
		t.Errorf("with -tests: got %v, err %v; want one finding", f, err)
	}
	if f, err := checkPath(dir, config{includeTests: false}); err != nil || len(f) != 0 {
		t.Errorf("with -tests=false: got %v, err %v; want none", f, err)
	}
}
