-- The bearer token goes away, and everything that follows from that.
--
-- 0009 gave a fleet's operators accounts and left the two shared bearer tokens in place: one per fleet
-- for scripts and first starts, one for the installation's own administrator. Removing them — which is
-- the point, because a shared credential names nobody and cannot be withdrawn from one person — makes
-- the platform administrator an account like everybody else, and leaves scripts needing a credential
-- that is not a password. So: one accounts table spanning both sides of the tenant boundary, sessions
-- keyed on the account rather than on a tenant, and a token per account that can be revoked by name.
--
-- **Why this is a second migration rather than an edit to 0009.** A migration is append-only from the
-- moment it can have run anywhere, which is the moment it is pushed — 0007 says so and gives the
-- reason. 0009 was pushed. Anybody who has run it has `operator_accounts`; this file has to take them
-- from there rather than pretend they are starting fresh, even though the two ship in the same change.
--
-- The shape 0009 chose was right for what it knew: an account belonged to a fleet, so it lived under
-- the same row-level security as a host. What changed is that there is now a kind of account that
-- belongs to no fleet, and two tables for the two kinds would have put the one constraint that matters
-- — an address identifies exactly one account across the installation — beyond what the database can
-- state. So the tenant becomes nullable and the policy grows a second disjunct instead.

-- ---------------------------------------------------------------------------------------------------
-- One accounts table, spanning both sides of the boundary.
-- ---------------------------------------------------------------------------------------------------

ALTER TABLE IF EXISTS operator_accounts RENAME TO accounts;
ALTER TABLE IF EXISTS operator_sessions RENAME TO sessions;

-- The primary key from 0009 is (tenant_id, id), which a NULL tenant cannot satisfy — and PostgreSQL
-- refuses to drop NOT NULL from a column while it is in one, so the key has to go first. The session
-- table's composite foreign key references that key, so it has to go before *that*: three statements
-- whose order is fixed by the database rather than by taste, which is why they are together.
--
-- An account id is 128 bits generated by the control plane, so it is unique across the installation by
-- construction rather than by hope — the same argument 0004 makes for host ids and certificate
-- fingerprints. That is what lets the key be the id alone, which in turn is what lets a session row
-- point at an account without carrying a tenant it has no business knowing.
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS operator_sessions_account_fk;
ALTER TABLE accounts DROP CONSTRAINT IF EXISTS operator_accounts_pkey;
ALTER TABLE accounts ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);

-- A platform administrator has no fleet, which is the whole of what makes them one. The foreign key to
-- tenants needs no change: an unmatched NULL is not checked, which is exactly the behaviour wanted.
ALTER TABLE accounts ALTER COLUMN tenant_id DROP NOT NULL;

-- ---------------------------------------------------------------------------------------------------
-- Sessions belong to an account, not to a fleet.
--
-- 0009 carried a tenant on the session row and keyed the policy on it, which was the honest reading of
-- "a session is one operator's". It stops being true the moment an account can have no tenant, and the
-- alternative was a nullable tenant whose foreign key would silently stop being checked — a session
-- claiming one fleet while naming another's account, refused by nothing.
--
-- So the column goes and the account is the single source of truth for which side of the boundary a
-- session is on. The policy below says exactly that, in the database, rather than leaving it to a
-- session setting whose value the caller chooses.
-- ---------------------------------------------------------------------------------------------------

-- The old policy and the old index both read the column, so both go before it does. The replacements
-- are further down with the rest of the row-level security, where they can be read together — this is
-- only the part PostgreSQL insists happens first.
DROP POLICY IF EXISTS operator_sessions_tenant_isolation ON sessions;
DROP INDEX  IF EXISTS operator_sessions_account;

ALTER TABLE sessions DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE sessions ADD CONSTRAINT sessions_account_fk
    FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE;

-- When the session was last used, for the list an operator reads before pressing "sign out
-- everywhere". It is what turns that list from six identical rows into one somebody can act on.
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS last_used_at timestamptz;

-- Where it was last used from, as the browser and the peer address reported it.
--
-- Advisory and clearly so: a user agent is a string the client chooses, and behind a proxy the address
-- is the proxy's. It is here because "that one is not me" is a judgement somebody makes from weak
-- evidence or not at all, and the alternative is a list of six sessions that are all just "a session".
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS user_agent text NOT NULL DEFAULT '';
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS sessions_account ON sessions (account_id, expires_at);

-- ---------------------------------------------------------------------------------------------------
-- A token per account, for the scripts the shared one used to serve.
--
-- It is a bearer token and that is not a contradiction with removing the other one. What was wrong
-- with `FARRIER_ADMIN_TOKEN` was not the word "bearer": it was one credential for a whole fleet, held
-- in a flag, naming nobody in the audit trail, never expiring, and withdrawable only by restarting the
-- control plane with a new one and telling everybody. This is a credential that belongs to a person,
-- acts as that person, expires, and is revoked from a page in a second.
--
-- Only the SHA-256 is stored, unsalted and unstretched, which is right here for the reason it is right
-- for an enrolment token and wrong for the password column two tables up: the input is 256 bits of
-- uniform randomness this process generated, so there is no dictionary to attack.
-- ---------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS api_tokens (
    hash         text        PRIMARY KEY,
    account_id   text        NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,

    -- What the operator called it, so that revoking the right one is possible. A token nobody can tell
    -- apart from the others is a token nobody revokes.
    label        text        NOT NULL DEFAULT '',

    created_at   timestamptz NOT NULL DEFAULT now(),

    -- When it stops working, NULL for never.
    --
    -- Nullable rather than a far-future date, because "this one does not expire" is a decision somebody
    -- made and should read as one — a token dated 2124 looks like a mistake and gets left alone.
    expires_at   timestamptz,

    -- When it was last used, so an unused token is visible as unused before somebody has to guess.
    last_used_at timestamptz
);

CREATE INDEX IF NOT EXISTS api_tokens_account ON api_tokens (account_id, created_at DESC);

-- ---------------------------------------------------------------------------------------------------
-- Row-level security, enabled and FORCED, on all three.
--
-- The accounts policy has three ways in and each says something different:
--
--   * a fleet's operator, through farrier.tenant, exactly as in 0009 and for every other tenant table;
--   * the installation's own administrators, through farrier.platform — a NULL tenant is unreachable
--     from any fleet, because `NULL = 'anything'` is NULL and not true, so this is the only door to
--     those rows;
--   * one named row, through farrier.resolve_key, for the two lookups that must happen before either
--     of the above is known: an address on a sign-in form, and an account id read out of a session.
--
-- The address is the one key here that is guessable, and 0009 wrote down what keeps that from being a
-- disclosure: the sign-in endpoint answers a wrong address and a wrong password identically, in the
-- same time, under a rate limit. That is still true and still load-bearing. An account id is not
-- guessable, and the only way to hold one is to have already resolved a session token to it.
-- ---------------------------------------------------------------------------------------------------

DROP POLICY IF EXISTS operator_accounts_tenant_isolation ON accounts;
DROP POLICY IF EXISTS accounts_tenant_isolation ON accounts;
CREATE POLICY accounts_tenant_isolation ON accounts
    USING      (tenant_id = current_setting('farrier.tenant', true)
                OR (tenant_id IS NULL AND current_setting('farrier.platform', true) = 'on')
                OR email_key = current_setting('farrier.resolve_key', true)
                OR id = current_setting('farrier.resolve_key', true))
    WITH CHECK (tenant_id = current_setting('farrier.tenant', true)
                OR (tenant_id IS NULL AND current_setting('farrier.platform', true) = 'on'));

-- A credential is reachable by its own hash, or through the account that owns it. Nothing else.
--
-- The second half is a subquery on purpose, and it is the difference between a boundary the database
-- holds and one it merely records. The obvious spelling is a farrier.account session setting compared
-- against account_id — but the value in such a setting is one the caller picked, so a request naming
-- somebody else's account id would be handed their sessions by the very policy whose job was to refuse
-- it. The subquery asks the question that actually matters instead: *can this transaction see that
-- account?* PostgreSQL applies row-level security to a table referenced inside a policy expression, so
-- the answer comes from the accounts policy above — a fleet's rows through farrier.tenant, the
-- installation's own through farrier.platform, and no way to reach across either. A session is visible
-- exactly when its owner is, an insert is allowed exactly when its owner is, and a method written later
-- that forgets to check inherits both without knowing it.
--
-- There is deliberately no listing that is not per account: "every session on this installation" is a
-- question nothing has a reason to ask.
DROP POLICY IF EXISTS sessions_account_isolation ON sessions;
CREATE POLICY sessions_account_isolation ON sessions
    USING      (token_hash = current_setting('farrier.resolve_key', true)
                OR EXISTS (SELECT 1 FROM accounts a WHERE a.id = sessions.account_id))
    WITH CHECK (EXISTS (SELECT 1 FROM accounts a WHERE a.id = sessions.account_id));

ALTER TABLE api_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_tokens FORCE  ROW LEVEL SECURITY;

DROP POLICY IF EXISTS api_tokens_account_isolation ON api_tokens;
CREATE POLICY api_tokens_account_isolation ON api_tokens
    USING      (hash = current_setting('farrier.resolve_key', true)
                OR EXISTS (SELECT 1 FROM accounts a WHERE a.id = api_tokens.account_id))
    WITH CHECK (EXISTS (SELECT 1 FROM accounts a WHERE a.id = api_tokens.account_id));
