package store

import (
	"context"
	"fmt"
	"sort"
	"time"
)

// wallboardShareRow is a share together with the tenant that published it.
//
// WallboardShare itself carries no tenant, because nothing outside the store chooses one — the tenant
// comes from the handle the caller had to obtain, and the published key's own tenant segment is
// resolved before this layer is reached. It has to be recorded beside the record all the same, since
// every read filters on it, which is the same shape hostRow and tokenRow take.
type wallboardShareRow struct {
	// share is the record as callers see it.
	share WallboardShare

	// tenant is the fleet whose status screen it publishes.
	tenant TenantID
}

// CreateWallboardShare records a link that publishes this fleet's status screen.
//
// The cap is counted under the store's one lock, which makes it atomic here in the way the single
// conditional INSERT makes it atomic in PostgreSQL: two goroutines publishing at once cannot both read
// nineteen. That is stricter than the shipped store manages under READ COMMITTED, and the difference is
// written down at the PostgreSQL method rather than papered over here — a memory-backed test must not
// be able to prove a bound the database does not hold.
//
// Liveness is counted against the wall clock rather than against the share's own CreatedAt, matching
// the `now()` in the SQL: a fixture that backdates a creation time is describing when the link was
// published, not asking for a cap computed in the past.
func (s *scopedMemory) CreateWallboardShare(_ context.Context, share WallboardShare) error {
	m := s.store
	m.mu.Lock()
	defer m.mu.Unlock()

	if _, ok := m.tenants[s.tenant]; !ok {
		return errUnknownTenant(s.tenant)
	}

	now := time.Now().UTC()
	live := 0
	for _, row := range m.shares {
		if row.tenant == s.tenant && row.share.Live(now) {
			live++
		}
	}
	// Before the uniqueness checks below, because that is the order the SQL evaluates them in: a
	// conditional INSERT whose WHERE is false inserts nothing at all, so a fleet at its cap is told it
	// is at its cap even when the id it offered was also taken.
	if live >= MaxWallboardSharesPerTenant {
		return fmt.Errorf("%w: this fleet already holds %d live wallboard shares",
			ErrConflict, MaxWallboardSharesPerTenant)
	}

	// Keyed by id alone, like hosts and accounts and for the same reason: a share id is generated by
	// the control plane from 128 bits of randomness, so two fleets cannot hold the same one. That makes
	// this check marginally stricter than the schema's (tenant_id, id) primary key, which is the safe
	// direction — a test cannot create a pair here that PostgreSQL would then refuse.
	if _, exists := m.shares[share.ID]; exists {
		return ErrConflict
	}
	for _, row := range m.shares {
		if row.tenant == s.tenant && row.share.SecretHash == share.SecretHash {
			return ErrConflict
		}
	}

	if share.CreatedAt.IsZero() {
		share.CreatedAt = now
	}
	m.shares[share.ID] = wallboardShareRow{share: share, tenant: s.tenant}
	return nil
}

// ListWallboardShares returns this fleet's shares, newest first, expired ones included.
//
// Expired ones are listed rather than filtered, which is the whole reason the listing is not written in
// terms of Live: a share that has stopped working is the first thing somebody looks for when the screen
// in the corridor has gone dark.
func (s *scopedMemory) ListWallboardShares(_ context.Context) ([]WallboardShare, error) {
	s.store.mu.Lock()
	defer s.store.mu.Unlock()

	var out []WallboardShare
	for _, row := range s.store.shares {
		if row.tenant != s.tenant {
			continue
		}
		out = append(out, row.share)
	}
	sort.Slice(out, func(i, j int) bool {
		if !out[i].CreatedAt.Equal(out[j].CreatedAt) {
			return out[i].CreatedAt.After(out[j].CreatedAt)
		}
		// The tiebreak keeps the order deterministic when a test publishes two shares inside one clock
		// tick, which would otherwise flake by map order.
		return out[i].ID < out[j].ID
	})
	return out, nil
}

// WallboardShareBySecret returns the live share whose secret hashes to this, or ErrNotFound.
//
// Unknown, withdrawn and expired are one answer here as they are in the SQL. Written as one condition
// rather than as three returns, because three refusals are three things to keep matched and the one
// that drifted would be the one telling a stranger which of their guesses had once been a link.
func (s *scopedMemory) WallboardShareBySecret(_ context.Context, secretHash string,
	now time.Time) (WallboardShare, error) {

	s.store.mu.Lock()
	defer s.store.mu.Unlock()

	for _, row := range s.store.shares {
		if row.tenant == s.tenant && row.share.SecretHash == secretHash && row.share.Live(now) {
			return row.share, nil
		}
	}
	return WallboardShare{}, ErrNotFound
}

// DeleteWallboardShare removes one share by id, or returns ErrNotFound.
//
// A share belonging to another fleet is not found rather than refused, which is the answer every other
// method here gives and the one row-level security gives in the shipped store: the identifier simply
// does not match anything this handle can see.
func (s *scopedMemory) DeleteWallboardShare(_ context.Context, id string) error {
	s.store.mu.Lock()
	defer s.store.mu.Unlock()

	row, ok := s.store.shares[id]
	if !ok || row.tenant != s.tenant {
		return ErrNotFound
	}
	delete(s.store.shares, id)
	return nil
}

// TouchWallboardShare stamps when a screen last polled one share, best effort.
//
// A share that has gone is deliberately not an error, matching the shipped store: the poll that stamped
// it is about to be refused by the lookup that follows, and a second refusal here would be one log line
// per revoked screen per poll. Another fleet's share is left alone by the same condition, so the
// silence covers only a row this fleet no longer has.
func (s *scopedMemory) TouchWallboardShare(_ context.Context, id string, at time.Time) error {
	s.store.mu.Lock()
	defer s.store.mu.Unlock()

	row, ok := s.store.shares[id]
	if !ok || row.tenant != s.tenant {
		return nil
	}
	row.share.LastSeenAt = at
	s.store.shares[id] = row
	return nil
}
