package store

import (
	"context"
	"errors"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/pascalgross/farrier/internal/protocol"
)

// sharedMachineID is one physical machine's identity, enrolled into both tenants below.
//
// The schema makes the machine-id claim per tenant rather than per installation, because across
// tenants it would be an oracle: enrolling a machine and being told it is already enrolled tells you
// that somebody else manages it. That the same hash can be live twice is therefore a property worth
// asserting, and it is one a store keyed on the hash alone would fail.
const sharedMachineID = "sha256:one-physical-machine"

// sharedJobID is the identifier both tenants choose for a job.
//
// This is the collision that actually happens. A signed job's id comes from the customer's own offline
// signer and is theirs to pick, so "01JSHAREDJOB" — or "reboot-2026-08-23" — is a reasonable thing for
// two customers to choose on the same day. Host ids are not in this category: they are generated here
// and stay globally unique, which is why the two tenants below have different ones.
const sharedJobID = "01JSHAREDJOB"

// twoTenants builds two populated tenants against one store, for the isolation tests.
//
// They collide everywhere the schema allows a collision — the same job id, the same machine-id hash —
// because that is what a leak would have to return in order to look like the caller's own data. Two
// tenants built from entirely distinct identifiers would pass against a store with no isolation at all,
// since there would be nothing for a broken query to hand back that a test could recognise as wrong.
//
// Alpha requires a second person to release a destructive job and beta requires nothing, so the two
// also differ in the setting most likely to be read from the wrong row.
func twoTenants(t *testing.T, s Store) (alpha, beta Scoped) {
	t.Helper()

	alpha = testTenant(t, s, "alpha", ApprovalSecondPerson)
	beta = testTenant(t, s, "beta", ApprovalNone)

	ctx := context.Background()
	for _, tenant := range []struct {
		// scoped is the handle, and hostID is the host enrolled into it.
		scoped Scoped
		hostID string
	}{{alpha, alphaHostID}, {beta, betaHostID}} {
		enrolTestHostAs(t, tenant.scoped, tenant.hostID, "web-01.example.org", sharedMachineID)

		if err := tenant.scoped.CreateEnrollmentToken(ctx, EnrollmentToken{
			Hash:      "hash-" + string(tenant.scoped.Tenant()),
			Label:     string(tenant.scoped.Tenant()) + "-token",
			Group:     "web-prod",
			CreatedAt: time.Now().UTC(),
			ExpiresAt: time.Now().UTC().Add(time.Hour),
		}); err != nil {
			t.Fatalf("creating a token for %s: %v", tenant.scoped.Tenant(), err)
		}

		job := jobFor(sharedJobID, "host.reboot")
		job.Class = "destructive"
		job.Signature = "c2ln"
		if err := tenant.scoped.CreateJob(ctx, NewJob{
			Job:                      job,
			HostID:                   tenant.hostID,
			CreatedBy:                "test:" + string(tenant.scoped.Tenant()),
			ApprovalRequired:         tenant.scoped == alpha,
			ApprovalDistinctOperator: tenant.scoped == alpha,
		}); err != nil {
			t.Fatalf("creating a job for %s: %v", tenant.scoped.Tenant(), err)
		}
	}
	return alpha, beta
}

// The two hosts, one per tenant.
//
// Different identifiers because host ids are generated by the control plane and are globally unique by
// construction — the collision worth testing is the one an operator can cause, which is the job id.
const (
	// alphaHostID is the host in the first tenant.
	alphaHostID = "01JALPHAHOST"

	// betaHostID is the host in the second, and the id every write probe below aims at.
	betaHostID = "01JBETAHOST"

	// betaJobID is a job only beta has, for the probes that must fail to reach it.
	betaJobID = "01JBETAJOB"
)

// TestGuaranteeOneTenantCannotSeeAnother is the isolation boundary, asserted rather than assumed.
//
// It is driven by reflection over the Scoped interface rather than by a list of calls, and that is the
// whole point of it. A hand-written list is a list somebody adds a method without joining, and the
// method they forget will be the new one — written in a hurry, reviewed as an addition rather than as a
// boundary. Here, a method added to Scoped and not named below fails the test until somebody decides
// what "isolated" means for it.
//
// What it proves is narrow and worth stating exactly: for every method on Scoped, calling it on
// tenant A against a store that also holds tenant B's data must not return B's data and must not
// mutate it. It does not prove the SQL is right — PostgreSQL's row-level security proves that, and
// TestGuaranteeRowLevelSecurityIsTheRuleNotThePredicate proves the policy is switched on.
func TestGuaranteeOneTenantCannotSeeAnother(t *testing.T) {
	eachStore(t, func(t *testing.T, s Store) {
		ctx := context.Background()
		alpha, beta := twoTenants(t, s)

		// Every method on Scoped, and what "isolated" means for each. A method missing from here fails
		// the completeness check below.
		probes := map[string]func(t *testing.T){
			"Tenant": func(t *testing.T) {
				if alpha.Tenant() == beta.Tenant() {
					t.Fatal("two tenants report the same identity")
				}
			},

			// Reads: a colliding identifier must resolve to the caller's own row, and a listing must
			// contain only the caller's rows.
			"GetHost": func(t *testing.T) {
				host, err := alpha.GetHost(ctx, alphaHostID)
				if err != nil {
					t.Fatalf("alpha cannot read its own host: %v", err)
				}
				if host.Hostname != "web-01.example.org" {
					t.Fatalf("read back %+v", host)
				}
				// Proved by the job below rather than by the host row, which is identical in both.
				job, err := alpha.GetJob(ctx, sharedJobID)
				if err != nil {
					t.Fatalf("alpha cannot read its own job: %v", err)
				}
				if job.CreatedBy != "test:"+string(alpha.Tenant()) {
					t.Errorf("alpha read a job created by %q, which is not its own", job.CreatedBy)
				}
			},
			"GetHostByMachineID": func(t *testing.T) {
				// The same machine-id hash is live in both, which the schema now permits per tenant.
				host, err := alpha.GetHostByMachineID(ctx, sharedMachineID)
				if err != nil {
					t.Fatalf("alpha cannot find its own host by machine id: %v", err)
				}
				if host.ID != alphaHostID {
					t.Fatalf("found %+v", host)
				}
			},
			"ListHosts": func(t *testing.T) {
				hosts, err := alpha.ListHosts(ctx)
				if err != nil {
					t.Fatalf("listing: %v", err)
				}
				if len(hosts) != 1 {
					t.Fatalf("alpha sees %d hosts; it has one and beta has one", len(hosts))
				}
			},
			"ListJobs": func(t *testing.T) {
				jobs, err := alpha.ListJobs(ctx, JobFilter{})
				if err != nil {
					t.Fatalf("listing: %v", err)
				}
				if len(jobs) != 1 {
					t.Fatalf("alpha sees %d jobs; it has one and beta has one", len(jobs))
				}
				if jobs[0].CreatedBy != "test:"+string(alpha.Tenant()) {
					t.Errorf("alpha's listing contains a job created by %q", jobs[0].CreatedBy)
				}
			},
			"GetJob": func(t *testing.T) {
				job, err := alpha.GetJob(ctx, sharedJobID)
				if err != nil {
					t.Fatalf("alpha cannot read its own job: %v", err)
				}
				if job.CreatedBy != "test:"+string(alpha.Tenant()) {
					t.Errorf("alpha read beta's job: created by %q", job.CreatedBy)
				}
			},
			"ListEnrollmentTokens": func(t *testing.T) {
				tokens, err := alpha.ListEnrollmentTokens(ctx)
				if err != nil {
					t.Fatalf("listing: %v", err)
				}
				// By content rather than by count: the probes run in map order, so another of them may
				// already have added a token of alpha's. What must never appear is beta's.
				var mine bool
				for _, token := range tokens {
					if token.Hash == "hash-"+string(beta.Tenant()) {
						t.Error("alpha's token listing contains a token issued to beta")
					}
					if token.Label == string(alpha.Tenant())+"-token" {
						mine = true
					}
				}
				if !mine {
					t.Fatalf("alpha's own token is missing from its listing: %+v", tokens)
				}
			},

			// Writes: an operation aimed at another tenant's row must fail, and must leave it alone.
			"CreateJob": func(t *testing.T) {
				// Aimed at beta's host id, from alpha. The id exists — in beta — so a store with no
				// isolation would accept it and file alpha's job against beta's machine.
				job := jobFor("01JCROSS", "facts.collect")
				err := alpha.CreateJob(ctx, NewJob{
					Job: job, HostID: betaHostID, CreatedBy: "test:alpha",
				})
				if !errors.Is(err, ErrNotFound) {
					t.Fatalf("creating a job for a host alpha does not have returned %v, want ErrNotFound", err)
				}
			},
			"ApproveJob": func(t *testing.T) {
				before, err := beta.GetJob(ctx, sharedJobID)
				if err != nil {
					t.Fatalf("reading beta's job: %v", err)
				}
				// Alpha releasing what it believes is its own job must not release beta's, even though
				// the id is identical and beta's is waiting for exactly this.
				_ = alpha.ApproveJob(ctx, sharedJobID, "test:someone-else", time.Now().UTC())

				after, err := beta.GetJob(ctx, sharedJobID)
				if err != nil {
					t.Fatalf("re-reading beta's job: %v", err)
				}
				if after.ApprovedBy != before.ApprovedBy || !after.ApprovedAt.Equal(before.ApprovedAt) {
					t.Fatalf("alpha released beta's job: approved by %q at %s",
						after.ApprovedBy, after.ApprovedAt)
				}
			},
			"RevokeHost": func(t *testing.T) {
				_ = alpha.RevokeHost(ctx, betaHostID)
				host, err := beta.GetHost(ctx, betaHostID)
				if err != nil {
					t.Fatalf("reading beta's host: %v", err)
				}
				if host.Revoked {
					t.Fatal("alpha revoked a host belonging to beta")
				}
			},
			"DeleteHost": func(t *testing.T) {
				_ = alpha.DeleteHost(ctx, betaHostID)
				if _, err := beta.GetHost(ctx, betaHostID); err != nil {
					t.Fatalf("alpha deleted a host belonging to beta: %v", err)
				}
			},
			"RecordHeartbeat": func(t *testing.T) {
				_ = alpha.RecordHeartbeat(ctx, betaHostID, HeartbeatUpdate{
					AgentVersion: "forged", LastSeen: time.Now().UTC(),
				})
				host, err := beta.GetHost(ctx, betaHostID)
				if err != nil {
					t.Fatalf("reading beta's host: %v", err)
				}
				if host.AgentVersion == "forged" {
					t.Fatal("alpha wrote a heartbeat onto a host belonging to beta")
				}
			},
			"StoreFacts": func(t *testing.T) {
				assertDocumentIsNotWritable(t, ctx, alpha.StoreFacts, beta, func(h Host) string {
					return h.FactsDigest
				})
			},
			"StorePolicy": func(t *testing.T) {
				assertDocumentIsNotWritable(t, ctx, alpha.StorePolicy, beta, func(h Host) string {
					return h.PolicyDigest
				})
			},
			"StoreSigners": func(t *testing.T) {
				assertDocumentIsNotWritable(t, ctx, alpha.StoreSigners, beta, func(h Host) string {
					return h.SignersDigest
				})
			},
			"ClaimJobs": func(t *testing.T) {
				// Beta's host has a claimable job waiting on it. Alpha claiming for that host id — an
				// id it does not own, but one it could learn from a log line or a support ticket — must
				// come back empty, and must not take beta's work off beta's queue on the way.
				claimed, err := alpha.ClaimJobs(ctx, betaHostID, 10)
				if err != nil {
					t.Fatalf("claiming: %v", err)
				}
				if len(claimed) != 0 {
					t.Fatalf("alpha claimed %d job(s) for a host belonging to beta: %+v",
						len(claimed), claimed)
				}
				// And beta's job is still there to be claimed, rather than having been consumed by a
				// claim that then discarded it — which would deliver the job to nobody at all.
				stillThere, err := beta.ClaimJobs(ctx, betaHostID, 10)
				if err != nil {
					t.Fatalf("beta claiming its own work: %v", err)
				}
				if len(stillThere) == 0 {
					t.Fatal("alpha's claim consumed beta's job without delivering it")
				}
			},
			"RecordResult": func(t *testing.T) {
				err := alpha.RecordResult(ctx, betaHostID, protocol.ResultRequest{
					JobID: betaJobID, Status: protocol.StatusSucceeded,
				})
				if !errors.Is(err, ErrNotFound) {
					t.Fatalf("alpha reported a result for beta's job and got %v, want ErrNotFound", err)
				}
			},
			"CreateEnrollmentToken": func(t *testing.T) {
				// A token created by alpha must not appear in beta's listing, which is the leak that
				// would let one customer enrol a machine into another's fleet.
				if err := alpha.CreateEnrollmentToken(ctx, EnrollmentToken{
					Hash: "hash-crossing", Label: "alpha-second", Group: "web-prod",
					CreatedAt: time.Now().UTC(), ExpiresAt: time.Now().UTC().Add(time.Hour),
				}); err != nil {
					t.Fatalf("creating a token: %v", err)
				}
				tokens, err := beta.ListEnrollmentTokens(ctx)
				if err != nil {
					t.Fatalf("listing beta's tokens: %v", err)
				}
				for _, token := range tokens {
					if token.Hash == "hash-crossing" {
						t.Fatal("a token alpha created is listed for beta")
					}
				}
			},
			"ConsumeEnrollmentToken": func(t *testing.T) {
				_, err := alpha.ConsumeEnrollmentToken(ctx, "hash-"+string(beta.Tenant()), "01JNEW", time.Now())
				if !errors.Is(err, ErrTokenUnusable) {
					t.Fatalf("alpha redeemed a token issued to beta: %v", err)
				}
			},
			"CreateEnrolledHost": func(t *testing.T) {
				// twoTenants enrols one host into each with the same machine-id hash, which the schema
				// permits per tenant and would refuse if the claim were installation-wide. What must
				// not follow is that either can then read the other's row.
				if _, err := beta.GetHost(ctx, betaHostID); err != nil {
					t.Fatalf("beta cannot read the host it enrolled: %v", err)
				}
				if _, err := alpha.GetHost(ctx, betaHostID); !errors.Is(err, ErrNotFound) {
					t.Fatalf("alpha read a host beta enrolled, getting %v; want ErrNotFound", err)
				}
			},
			"AddCertificate": func(t *testing.T) {
				err := alpha.AddCertificate(ctx, Certificate{
					Fingerprint: "fp-crossing", HostID: betaHostID, TenantID: alpha.Tenant(),
					Serial: "02", IssuedAt: time.Now(), NotAfter: time.Now().Add(time.Hour),
				})
				if err == nil {
					t.Fatal("alpha issued a certificate against a host belonging to beta")
				}
			},
		}

		// A second job that exists only in beta, for the write probes above to aim at. Beta's host is
		// already there from twoTenants; what is missing is a job alpha has no counterpart for, so that
		// a leak would have to return something alpha could not mistake for its own.
		if err := beta.CreateJob(ctx, NewJob{
			Job: jobFor(betaJobID, "facts.collect"), HostID: betaHostID, CreatedBy: "test:beta",
		}); err != nil {
			t.Fatalf("creating beta's private job: %v", err)
		}

		assertEveryScopedMethodIsProbed(t, probes)

		for name, probe := range probes {
			t.Run(name, probe)
		}
	})
}

// assertDocumentIsNotWritable checks that one tenant cannot write a reported document onto another's
// host.
//
// The three document setters have identical shapes and identical failure modes, so testing them by
// copy would mean three chances to check the wrong digest.
func assertDocumentIsNotWritable(
	t *testing.T,
	ctx context.Context,
	write func(context.Context, string, string, []byte) error,
	victim Scoped,
	digestOf func(Host) string,
) {
	t.Helper()

	_ = write(ctx, betaHostID, "sha256:forged", []byte(`{"forged":true}`))
	host, err := victim.GetHost(ctx, betaHostID)
	if err != nil {
		t.Fatalf("reading the victim's host: %v", err)
	}
	if digestOf(host) == "sha256:forged" {
		t.Fatal("one tenant wrote a document onto another tenant's host")
	}
}

// assertEveryScopedMethodIsProbed fails when Scoped has grown a method the isolation test does not
// cover.
//
// This is the half that makes the test above hold in a year rather than today. A boundary asserted by a
// list is a boundary that decays by addition: the method somebody forgets to add is the new one, which
// is also the one least likely to have been thought about. Reflecting over the interface makes
// forgetting a build failure instead of a silence.
func assertEveryScopedMethodIsProbed(t *testing.T, probes map[string]func(*testing.T)) {
	t.Helper()

	scoped := reflect.TypeOf((*Scoped)(nil)).Elem()
	var missing []string
	for i := range scoped.NumMethod() {
		if _, covered := probes[scoped.Method(i).Name]; !covered {
			missing = append(missing, scoped.Method(i).Name)
		}
	}
	if len(missing) > 0 {
		t.Fatalf("Scoped has %d method(s) with no isolation probe: %s.\n"+
			"Every method that reaches a tenant's data needs one, because the method nobody thought to "+
			"add is the method nobody thought about. Add a case to the map above saying what "+
			"\"isolated\" means for it.",
			len(missing), strings.Join(missing, ", "))
	}

	for name := range probes {
		if _, exists := scoped.MethodByName(name); !exists {
			t.Errorf("the isolation test probes %q, which Scoped no longer has", name)
		}
	}
}

// TestGuaranteeRowLevelSecurityIsTheRuleNotThePredicate proves the database refuses the row, and not
// merely that the queries remember to ask.
//
// Everything else about isolation could be true and this could still be false: every statement in
// postgres.go could carry its tenant predicate, every test above could pass, and the policies could be
// absent — leaving one forgotten WHERE clause between a customer and somebody else's fleet. So this
// runs a statement with no predicate at all, which no production query does, and requires the answer to
// be scoped anyway.
//
// It is PostgreSQL-only because the mechanism is. The in-memory store enforces the same rule in Go and
// is covered by the test above; this asserts the thing that cannot be asserted anywhere but here.
func TestGuaranteeRowLevelSecurityIsTheRuleNotThePredicate(t *testing.T) {
	pg := newPostgres(t)
	ctx := context.Background()
	alpha, beta := twoTenants(t, pg)

	// The role has to be one the policies apply to. A superuser, or a role with BYPASSRLS, is exempt
	// from every policy in the schema with no symptom whatsoever — so a suite run as one would pass
	// this test while proving the opposite of what it claims. farrier-server refuses to start on such a
	// role for the same reason; here it is a failure rather than a skip, because a guarantee test that
	// quietly opted out would be worse than none.
	var role string
	var superuser, bypass bool
	if err := pg.pool.QueryRow(ctx,
		`SELECT rolname, rolsuper, rolbypassrls FROM pg_roles WHERE rolname = current_user`,
	).Scan(&role, &superuser, &bypass); err != nil {
		t.Fatalf("reading the current role: %v", err)
	}
	if superuser || bypass {
		t.Fatalf("these tests connect as %q, which bypasses row-level security, so they cannot "+
			"observe it. Run them as an ordinary role: CREATE ROLE farrier_test LOGIN; and grant it "+
			"the schema", role)
	}

	for _, table := range []string{"hosts", "jobs", "certificates", "enrollment_tokens"} {
		t.Run(table, func(t *testing.T) {
			// No tenant set at all. Fail closed: current_setting(…, true) is NULL when unset, and
			// `tenant_id = NULL` is NULL rather than true, so the policy admits nothing.
			var unscoped int
			if err := pg.pool.QueryRow(ctx, `SELECT count(*) FROM `+table).Scan(&unscoped); err != nil {
				t.Fatalf("counting %s with no tenant set: %v", table, err)
			}
			if unscoped != 0 {
				t.Errorf("a query against %s with no tenant set returned %d rows; the policy is not "+
					"enabled, or not FORCEd, and the table owner is bypassing it", table, unscoped)
			}

			// One tenant set, and a statement with no predicate of its own. Both tenants have rows
			// here; only one may come back.
			for _, tenant := range []Scoped{alpha, beta} {
				var seen int
				err := countAsTenant(ctx, pg, tenant.Tenant(), table, &seen)
				if err != nil {
					t.Fatalf("counting %s as %s: %v", table, tenant.Tenant(), err)
				}
				var total int
				if err := countAsTenant(ctx, pg, tenant.Tenant(), table+" WHERE true", &total); err != nil {
					t.Fatalf("counting %s: %v", table, err)
				}
				if seen == 0 {
					t.Errorf("%s sees none of its own rows in %s", tenant.Tenant(), table)
				}
				if seen != total {
					t.Errorf("%s sees %d rows in %s unfiltered and %d filtered", tenant.Tenant(), seen, table, total)
				}
			}
		})
	}

	// And the same for a write: the policy's WITH CHECK must refuse a row addressed to somebody else.
	tx, err := pg.pool.Begin(ctx)
	if err != nil {
		t.Fatalf("beginning: %v", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()
	if _, err := tx.Exec(ctx,
		`SELECT set_config('farrier.tenant', $1, true)`, string(alpha.Tenant())); err != nil {
		t.Fatalf("setting the tenant: %v", err)
	}
	_, err = tx.Exec(ctx,
		`INSERT INTO hosts (id, hostname, tenant_id, enrolled_at) VALUES ($1, $2, $3, now())`,
		"01JSTOLEN", "stolen", string(beta.Tenant()))
	if err == nil {
		t.Error("a tenant inserted a host row belonging to another tenant; the policy has no WITH CHECK")
	}
}

// countAsTenant runs a bare count inside a transaction that has set one tenant.
//
// The statement it runs deliberately has no tenant predicate. That is what is being tested: a query
// written by somebody who forgot must return that tenant's rows and no others, because the policy is
// the rule and the predicate is only the query plan.
func countAsTenant(ctx context.Context, pg *Postgres, tenant TenantID, from string, into *int) error {
	tx, err := pg.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if _, err := tx.Exec(ctx, `SELECT set_config('farrier.tenant', $1, true)`, string(tenant)); err != nil {
		return err
	}
	return tx.QueryRow(ctx, `SELECT count(*) FROM `+from).Scan(into)
}

// TestGuaranteeDeletingATenantLeavesNothingBehind is the other half of isolation: what a customer
// leaves behind when they go.
//
// It matters for the same reason the boundary does. A tenant's rows outliving the tenant would mean a
// deleted customer's hostnames, policies and job history sitting in a database somebody has been told
// is empty of them — and, because a job row references a host, it would also be the shape of a
// dangling reference that resurfaces as somebody else's row after an id is reused.
func TestGuaranteeDeletingATenantLeavesNothingBehind(t *testing.T) {
	eachStore(t, func(t *testing.T, s Store) {
		ctx := context.Background()
		alpha, beta := twoTenants(t, s)

		if err := s.DeleteTenant(ctx, alpha.Tenant()); err != nil {
			t.Fatalf("deleting alpha: %v", err)
		}

		if _, err := s.GetTenant(ctx, alpha.Tenant()); !errors.Is(err, ErrNotFound) {
			t.Errorf("the deleted tenant is still readable: %v", err)
		}
		if _, err := alpha.GetHost(ctx, alphaHostID); !errors.Is(err, ErrNotFound) {
			t.Errorf("a deleted tenant's host is still readable: %v", err)
		}
		if _, err := alpha.GetJob(ctx, sharedJobID); !errors.Is(err, ErrNotFound) {
			t.Errorf("a deleted tenant's job is still readable: %v", err)
		}
		if jobs, err := alpha.ListJobs(ctx, JobFilter{}); err != nil || len(jobs) != 0 {
			t.Errorf("a deleted tenant lists %d job(s): %v", len(jobs), err)
		}
		if tokens, err := alpha.ListEnrollmentTokens(ctx); err != nil || len(tokens) != 0 {
			t.Errorf("a deleted tenant lists %d token(s): %v", len(tokens), err)
		}

		// The certificate is the one that would still authenticate. An agent presents it on every
		// request, and a row that survived its tenant would let a deleted customer's machine keep
		// talking to the control plane.
		if _, err := s.LookupCertificate(ctx, "fp-"+string(alpha.Tenant())+"-"+alphaHostID); !errors.Is(err, ErrNotFound) {
			t.Errorf("a deleted tenant's certificate still authenticates: %v", err)
		}

		// And the neighbour is untouched, which is the half that would be missed by a delete that was
		// too enthusiastic rather than too timid.
		if _, err := beta.GetHost(ctx, betaHostID); err != nil {
			t.Errorf("deleting alpha removed beta's host: %v", err)
		}
		if _, err := beta.GetJob(ctx, sharedJobID); err != nil {
			t.Errorf("deleting alpha removed beta's job: %v", err)
		}
		if _, err := s.LookupCertificate(ctx, "fp-"+string(beta.Tenant())+"-"+betaHostID); err != nil {
			t.Errorf("deleting alpha removed beta's certificate: %v", err)
		}
	})
}

// TestGuaranteeATenantsApprovalModeCannotRewriteAJobAlreadyQueued is the rule that makes the setting
// safe to expose.
//
// A destructive job records what it required when it was created. Reading the tenant's mode at approval
// time instead would defeat the second-person rule in two API calls: queue the job while the tenant
// requires a second person, relax the setting, release it yourself. That is not a hypothetical — the
// setting is editable through the API by exactly the operator who would benefit.
func TestGuaranteeATenantsApprovalModeCannotRewriteAJobAlreadyQueued(t *testing.T) {
	eachStore(t, func(t *testing.T, s Store) {
		ctx := context.Background()
		tenant := testTenant(t, s, "alpha", ApprovalSecondPerson)
		enrolTestHost(t, tenant, "01JHOSTA", "a.example.org")

		job := jobFor("01JREBOOT", "host.reboot")
		job.Class = "destructive"
		job.Signature = "c2ln"
		if err := tenant.CreateJob(ctx, NewJob{
			Job: job, HostID: "01JHOSTA", CreatedBy: "test:alice",
			ApprovalRequired: true, ApprovalDistinctOperator: true,
		}); err != nil {
			t.Fatalf("creating the job: %v", err)
		}

		// The operator relaxes their own fleet's rule, which is a thing they are allowed to do.
		stored, err := s.GetTenant(ctx, tenant.Tenant())
		if err != nil {
			t.Fatalf("reading the tenant: %v", err)
		}
		stored.ApprovalMode = ApprovalNone
		if err := s.UpdateTenant(ctx, stored); err != nil {
			t.Fatalf("relaxing the tenant: %v", err)
		}

		// And it changes nothing about the job they already queued.
		if err := tenant.ApproveJob(ctx, "01JREBOOT", "test:alice", time.Now().UTC()); !errors.Is(err, ErrConflict) {
			t.Fatalf("the job's creator released it after relaxing the tenant: %v", err)
		}
		rec, err := tenant.GetJob(ctx, "01JREBOOT")
		if err != nil {
			t.Fatalf("reading the job: %v", err)
		}
		if rec.Claimable() {
			t.Fatal("relaxing the tenant made an already-queued job claimable without a release")
		}

		// A second person still releases it, under the rule it was created with.
		if err := tenant.ApproveJob(ctx, "01JREBOOT", "test:bob", time.Now().UTC()); err != nil {
			t.Fatalf("a second operator could not release it: %v", err)
		}
	})
}

// TestGuaranteeATenantThatNeedsNoApprovalStillNeedsASignature is the line the approval setting must
// never cross.
//
// Relaxing approval relaxes a control-plane control. It must not relax the one the guarantee in
// docs/SECURITY.md §1 actually rests on: a destructive job carries a signature made offline by a key in
// the host's own trusted-signers, and no tenant setting reaches that. The host is what enforces it, so
// this asserts the half the store is responsible for — that a job created under ApprovalNone arrives at
// the host with its signature intact and its class unchanged, rather than being quietly downgraded to
// something mTLS alone would authorise.
func TestGuaranteeATenantThatNeedsNoApprovalStillNeedsASignature(t *testing.T) {
	eachStore(t, func(t *testing.T, s Store) {
		ctx := context.Background()
		tenant := testTenant(t, s, "alpha", ApprovalNone)
		enrolTestHost(t, tenant, "01JHOSTA", "a.example.org")

		job := jobFor("01JREBOOT", "host.reboot")
		job.Class = "destructive"
		job.Signature = "c2lnbmF0dXJl"
		job.SignerKeyID = "ops-laptop"
		job.SignerAlgorithm = "ed25519"
		if err := tenant.CreateJob(ctx, NewJob{
			Job: job, HostID: "01JHOSTA", CreatedBy: "test:alice",
		}); err != nil {
			t.Fatalf("creating the job: %v", err)
		}

		claimed, err := tenant.ClaimJobs(ctx, "01JHOSTA", 10)
		if err != nil {
			t.Fatalf("claiming: %v", err)
		}
		if len(claimed) != 1 {
			t.Fatalf("a tenant requiring no release did not deliver its job: %+v", claimed)
		}
		switch {
		case claimed[0].Signature != "c2lnbmF0dXJl":
			t.Error("the signature did not survive a tenant that requires no approval")
		case claimed[0].SignerKeyID != "ops-laptop":
			t.Error("the signer identity did not survive")
		case claimed[0].Class != "destructive":
			t.Errorf("the class arrived as %q; a host takes the class from its own catalogue, but a "+
				"control plane that relabelled one is a control plane worth failing here",
				claimed[0].Class)
		}
	})
}

// TestGuaranteeAnUnusableTokenResolvesToNoTenant closes the gap between resolving a token and
// redeeming it.
//
// Enrolment resolves the token first, to find out which tenant's machine-id claim to check against, and
// redeems it afterwards. If the resolver answered for a token that could never be redeemed, an expired
// or already-used token would still steer a stranger's machine at a real tenant's rows for the length
// of one request — and the two implementations disagreed about this, which is the drift the shared
// suite exists to catch.
func TestGuaranteeAnUnusableTokenResolvesToNoTenant(t *testing.T) {
	eachStore(t, func(t *testing.T, s Store) {
		ctx := context.Background()
		tenant := testTenant(t, s, "alpha", ApprovalNone)
		now := time.Now().UTC()

		if err := tenant.CreateEnrollmentToken(ctx, EnrollmentToken{
			Hash: "hash-expired", Label: "expired", CreatedAt: now.Add(-2 * time.Hour),
			ExpiresAt: now.Add(-time.Hour),
		}); err != nil {
			t.Fatalf("creating an expired token: %v", err)
		}
		if err := tenant.CreateEnrollmentToken(ctx, EnrollmentToken{
			Hash: "hash-live", Label: "live", CreatedAt: now, ExpiresAt: now.Add(time.Hour),
		}); err != nil {
			t.Fatalf("creating a live token: %v", err)
		}

		if _, err := s.TenantForEnrollmentToken(ctx, "hash-live"); err != nil {
			t.Fatalf("a live token does not resolve: %v", err)
		}
		for _, hash := range []string{"hash-expired", "hash-never-existed"} {
			if _, err := s.TenantForEnrollmentToken(ctx, hash); !errors.Is(err, ErrTokenUnusable) {
				t.Errorf("%s resolved to a tenant, producing %v; want ErrTokenUnusable", hash, err)
			}
		}

		// And a token stops resolving the moment it is redeemed, rather than on the next expiry.
		enrolTestHost(t, tenant, "01JHOSTA", "a.example.org")
		if _, err := tenant.ConsumeEnrollmentToken(ctx, "hash-live", "01JHOSTA", now); err != nil {
			t.Fatalf("redeeming: %v", err)
		}
		if _, err := s.TenantForEnrollmentToken(ctx, "hash-live"); !errors.Is(err, ErrTokenUnusable) {
			t.Errorf("a redeemed token still resolves to its tenant: %v", err)
		}
	})
}
